services:
  - type: web
    name: barber-shop-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node ./dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://oussamabarber.netlify.app
    healthCheckPath: /api/health
    autoDeploy: true
